In [2]:
#Importing Necessary Package
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Read file from SPSS
df= pd.read_spss('C:/Users/Dell/Desktop/project/DN BATCH 6/Qudus/Qudus Friend 2.sav')

#print the first 10 cases
df.head(10)

#print the last 10 cases
df.tail(10)

,ACM_Type,Edu_Level,hospital,Age,PVC,Blood_Group,Sex,Genotype,PD,PD_Group,Age_Bracket,Pos_Neg
590,Sefl_Contained,Secondary,CIVIL SERVICE,21-25,21-30,AB+,Male,AS,NaN,nil,>15,Negative
591,Face_to_Face,No Formal Education,UITH,1-5,31-40,A+,Female,AA,NaN,nil,<5,Negative
592,Face_to_Face,No Formal Education,UITH,1-5,31-40,O+,Male,AC,NaN,nil,<5,Negative
593,Face_to_Face,No Formal Education,UITH,1-5,31-40,A+,Female,AC,2089.0,2000-3000,<5,Positive
594,Face_to_Face,No Formal Education,UITH,6-10,31-40,AB+,Male,AS,NaN,nil,5-15,Negative
595,Sefl_Contained,Secondary,SOBI,16-20,31-40,AB+,Female,AA,NaN,nil,>15,Negative
596,Sefl_Contained,Tertiary,GHI,36-40,<15,O+,Female,AA,1098.0,1000-2000,>15,Positive
597,Face_to_Face,Primary,UITH,6-10,31-40,O+,Male,AA,NaN,nil,5-15,Negative
598,Sefl_Contained,Secondary,SOBI,11-15,31-40,B+,Male,AA,NaN,nil,5-15,Negative
599,Face_to_Face,Primary,UITH,6-10,15-20,A+,Female,AA,NaN,nil,5-15,Negative

In [3]:
#Examining the data info
df.info()

#Education Level has 9 missing cases

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ACM_Type     600 non-null    category
 1   Edu_Level    600 non-null    category
 2   hospital     600 non-null    category
 3   Age          600 non-null    category
 4   PVC          600 non-null    category
 5   Blood_Group  600 non-null    category
 6   Sex          600 non-null    category
 7   Genotype     600 non-null    category
 8   PD           178 non-null    float64
 9   PD_Group     600 non-null    category
 10  Age_Bracket  600 non-null    category
 11  Pos_Neg      600 non-null    category
dtypes: category(11), float64(1)
memory usage: 13.3 KB

In [17]:
#Running the cross tabulation for the categorical variables against SNP
print("Chi-Square Analysis\n")
col=['ACM_Type','Edu_Level', 'hospital', 'PVC','Blood_Group', 'Sex','Genotype', 'Age_Bracket',]
alpha=0.05
for i in col:
    df_crosstab=pd.crosstab(df[i], df['Pos_Neg'], margins=True)
    print (df_crosstab)
    df_crosstab=df_crosstab.iloc[ :-1 , :-1]
    stat, p, dof, expected=chi2_contingency(df_crosstab)
    print("Chi-square between", i, "and Parasite Density Status")
    print("Chisquare Statz= ", stat)
    print("p-value= ", p)
    print("degree of freedom= ", dof)
    if p<=alpha:
        print("There is significant relationship between", i, "and Parasite Density Status")
        print("The reason is because the associated p-value (",round(p, 4),") is lesser than 0.05")
    else:
        print("There is no significant relationship between", i, "and Parasite Density Status")
        print("The reason is because the associated p-value (",round(p, 7),") is greater than 0.05")
    print("\n")

Chi-Square Analysis

Pos_Neg         Negative  Positive  All
ACM_Type
Face_to_Face         103       115  218
Sefl_Contained       319        63  382
All                  422       178  600
Chi-square between ACM_Type and Parasite Density Status
Chisquare Statz=  85.72847737433885
p-value=  2.064187365797288e-20
degree of freedom=  1
There is significant relationship between ACM_Type and Parasite Density Status
The reason is because the associated p-value ( 0.0 ) is lesser than 0.05


Pos_Neg              Negative  Positive  All
Edu_Level
No Formal Education        55        42   97
Primary                    52        38   90
Secondary                 146        34  180
Tertiary                  169        64  233
All                       422       178  600
Chi-square between Edu_Level and Parasite Density Status
Chisquare Statz=  25.999624776325476
p-value=  9.539132374743257e-06
degree of freedom=  3
There is significant relationship between Edu_Level and Parasite Density Status
The reason is because the associated p-value ( 0.0 ) is lesser than 0.05


Pos_Neg        Negative  Positive  All
hospital
CHC OKELELE          62        38  100
CIVIL SERVICE        68        32  100
GHI                  87        13  100
SOBI                 73        27  100
UITH                132        68  200
All                 422       178  600
Chi-square between hospital and Parasite Density Status
Chisquare Statz=  19.04254752649236
p-value=  0.0007709596787498985
degree of freedom=  4
There is significant relationship between hospital and Parasite Density Status
The reason is because the associated p-value ( 0.0008 ) is lesser than 0.05


Pos_Neg  Negative  Positive  All
PVC
15-20         105        45  150
21-30         118        89  207
31-40          89        28  117
<15           110        16  126
All           422       178  600
Chi-square between PVC and Parasite Density Status
Chisquare Statz=  36.86283132287805
p-value=  4.919351440127684e-08
degree of freedom=  3
There is significant relationship between PVC and Parasite Density Status
The reason is because the associated p-value ( 0.0 ) is lesser than 0.05


Pos_Neg      Negative  Positive  All
Blood_Group
A+                188        79  267
AB+                62        28   90
B+                 34        14   48
O+                138        57  195
All               422       178  600
Chi-square between Blood_Group and Parasite Density Status
Chisquare Statz=  0.11429398301298596
p-value=  0.9900685789706998
degree of freedom=  3
There is no significant relationship between Blood_Group and Parasite Density Status
The reason is because the associated p-value ( 0.9900686 ) is greater than 0.05


Pos_Neg  Negative  Positive  All
Sex
Female        233       103  336
Male          189        75  264
All           422       178  600
Chi-square between Sex and Parasite Density Status
Chisquare Statz=  0.25779608059015785
p-value=  0.61163833587493
degree of freedom=  1
There is no significant relationship between Sex and Parasite Density Status
The reason is because the associated p-value ( 0.6116383 ) is greater than 0.05


Pos_Neg   Negative  Positive  All
Genotype
AA             349       146  495
AC              37        14   51
AS              34        17   51
SS               2         1    3
All            422       178  600
Chi-square between Genotype and Parasite Density Status
Chisquare Statz=  0.474930325232446
p-value=  0.9243635623940166
degree of freedom=  3
There is no significant relationship between Genotype and Parasite Density Status
The reason is because the associated p-value ( 0.9243636 ) is greater than 0.05


Pos_Neg      Negative  Positive  All
Age_Bracket
5-15              132        78  210
<5                 23        20   43
>15               267        80  347
All               422       178  600
Chi-square between Age_Bracket and Parasite Density Status
Chisquare Statz=  18.743289678180133
p-value=  8.510329201206668e-05
degree of freedom=  2
There is significant relationship between Age_Bracket and Parasite Density Status
The reason is because the associated p-value ( 0.0001 ) is lesser than 0.05