As you write Python code, you may require your program to make decisions based on certain conditions, to achieve that you will use an if-statement.

In [ ]:
# Conditonals
# basic signature

# if <expression>:
    # do something

In [ ]:
'''the expression will result in a boolean value,
if the boolen value is True, then the block of code under the if statement is executed.'''
if 9 < 3:
    print('9 > 3')

In [ ]:
# an else statement provides the alternate decision to be taken whenever the 'if statement' evaluates as False
if 9 < 3:
    print('9 > 3')
else:
    print('9 is greater')

9 is greater

In [ ]:
# an elif statement is used when there are other conditions to consider, which is usually the case.

In [ ]:
# Prompt the user to enter a score as a floating-point number
score = float(input('Enter your score: '))

# Determine the grade based on the score
if score >= 90 and score <= 100:
    grade = 'A'
elif score >= 80 and score <= 89:
    grade = 'B'
elif score >= 70 and score <= 79:
    grade = 'C'
elif score >= 60 and score <= 69:
    grade = 'D'
else:
    # If the score is below 60, assign the grade 'F'
    grade = 'F'

# Print the calculated grade
print(f"Your grade is: {grade}")

Nested conditionals, also known as nested if statements, are a programming construct used to create a series of conditional checks within other conditional statements. In nested conditionals, one or more if statements (or other conditional constructs like switch statements) are placed inside another if statement. This allows you to test multiple conditions, and the execution of code blocks depends on the evaluation of these conditions.

Here's a basic example of nested conditionals in Python:

In [ ]:
# nested conditonals
age = float(input('Enter your age: '))
vaccinated = input('Enter vaccination status (Y/N): ')

if age < 5:
    if vaccinated == 'N':
        print('you are eligible')
        if 4 > 6:
          print('okay')
    elif vaccinated == 'Y':
        print('you have been vaccinated')
else:
    print('you are above the age')

In [ ]:
# loops
# for loops provide a means to iterate over a sequence

# for {dynamic_var} in {iterable}:
    # do something

# Define a list of days of the week
days = ['Monday', 'Tuesday', 'Wednessday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

# Use a for loop to iterate over the elements in the list
for i in days:
    # Print each day's name
    print(i)

When you run this code, it will loop through the days list, and for each day, it checks if the day is 'Wednesday' or 'Saturday'. Depending on the day, it sets the event variable, and then it prints both the day and the event for that day. The output will look something like this:

In [ ]:
# pairing with an if statement

# Initialize the event variable
event = ''

# Use a for loop to iterate over the elements in the list
for day in days:
    # Check if the day is 'Wednesday' or 'Saturday'
    if day == 'Wednessday' or day == 'Saturday':
        event = 'Live Class!'
    else:
        event = 'No event'

    # Print the day and the event for that day
    print(day, event)

When you run this code, it will loop through the days list, and for each day, it checks if the day is 'Wednesday' or 'Saturday'. Depending on the day, it sets the event variable, and then it prints both the day and the event for that day.

In [ ]:
# using the break keyword
# Use a for loop to iterate over the elements in the list
for day in days:
    # Check if the day is 'Wednesday'
    if day == 'Wednesday':
        # If it is, break out of the loop
        break

    # Print the day as long as it's not 'Wednesday'
    print(day)

What happens when you use **pass, break or continue** within a for loop?

In [ ]:
print("\U0001f914")

In [ ]:
# Initialize an empty list to store even numbers
even = []

# Use a for loop to iterate through numbers from 1 to 10
for i in range(1, 11):
    # Check if the current number is even
    if i % 2 == 0:
        # If it's even, append it to the 'even' list
        even.append(i)

# Print the list of even numbers
print(even)

In [ ]:
# Initialize a variable to store the sum of even numbers
sum_even = 0

# Use a for loop to iterate through numbers from 1 to 10
for i in range(1, 11):
    # Check if the current number is even
    if i % 2 == 0:
        # If it's even, add it to the 'sum_even' variable
        sum_even += i

# Print the sum of even numbers
print(sum_even)

In [ ]:
# Iterate through the characters in the string 'Tobi'
for i in 'Tobi':
    # Print each character
    print(i)

In [ ]:
revenue = {'months':['jan', 'feb', 'mar', 'apr', 'may','jun', 'jul','aug', 'sept', 'oct','nov', 'dec'],
          'monthly_sales': [120, 135, 150, 145, 155, 160, 170, 180, 190, 200, 210, 220]}

In [ ]:
for month, sales in revenue.items():
    print(month, sales)

months ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sept', 'oct', 'nov', 'dec']
monthly_sales [120, 135, 150, 145, 155, 160, 170, 180, 190, 200, 210, 220]

The zip function can be used to pair the months and their corresponding sales values.

In [ ]:
for month, sales in zip(revenue['months'], revenue['monthly_sales']):
    print(month.upper(), sales)

Looping over a pandas dataframe

In [ ]:
import pandas as pd
df = pd.DataFrame(revenue)

In [ ]:
df

In [ ]:
# Initialize an empty list to store the sales categories
sale_categories = []

# Iterate through the rows in the DataFrame 'df'
for index, rows in df.iterrows():
    # Extract the value in the 'monthly_sales' column for the current row
    sales = rows['monthly_sales']

    # Categorize the sales value into one of three categories: 'Low', 'Medium', or 'High'
    if sales < 150:
        category = 'Low'
    elif sales < 170:
        category = 'Medium'
    else:
        category = 'High'

    # Append the determined category to the 'sale_categories' list
    sale_categories.append(category)

# Add a new column called 'sales category' to the DataFrame 'df' and assign the sales categories to it
df['sales category'] = sale_categories

In [ ]:
# sales categories is a series of High, low, Medium values corresponding to the sales in each month respectively.
sale_categories

In [ ]:
# the DataFrame object has a new column or feature
df

   months  monthly_sales
0     jan            120
1     feb            135
2     mar            150
3     apr            145
4     may            155
5     jun            160
6     jul            170
7     aug            180
8    sept            190
9     oct            200
10    nov            210
11    dec            220

In [ ]:
for index, row in df.iterrows():

    # 'iterrows()' is a pandas DataFrame method used to iterate through the rows of the DataFrame.
    # It returns each row as a Series and provides the index (row label) of the current row.

    # 'index' represents the index (row label) of the current row in the DataFrame.
    # 'row' is a pandas Series containing the data for the current row.

    # Let's print the current row:
    print(row)

months           jan
monthly_sales    120
Name: 0, dtype: object
months           feb
monthly_sales    135
Name: 1, dtype: object
months           mar
monthly_sales    150
Name: 2, dtype: object
months           apr
monthly_sales    145
Name: 3, dtype: object
months           may
monthly_sales    155
Name: 4, dtype: object
months           jun
monthly_sales    160
Name: 5, dtype: object
months           jul
monthly_sales    170
Name: 6, dtype: object
months           aug
monthly_sales    180
Name: 7, dtype: object
months           sept
monthly_sales     190
Name: 8, dtype: object
months           oct
monthly_sales    200
Name: 9, dtype: object
months           nov
monthly_sales    210
Name: 10, dtype: object
months           dec
monthly_sales    220
Name: 11, dtype: object

While loops are a fundamental control flow structure in programming that enable the repetition of a block of code as long as a specific condition remains true. They are commonly used when the number of iterations or the exact termination point is unknown in advance. The loop continues executing as long as the condition is met and terminates once the condition becomes false.

In [ ]:
# while loops

# Initialize a counter variable to 0.
counter = 0

# Create a while loop that runs as long as the 'counter' is less than 10.
while counter < 10:
    # Print "hello" to the console.
    print("hello")

    # Increment the 'counter' by 1 to control the loop.
    counter = counter + 1
else:
    # This block of code is executed when the while loop terminates.
    print('loop has been terminated')

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
loop has been terminated

In [ ]:
print(counter)

10

In [ ]:
# adding a break statment to a while loop
counter = 0
while counter < 10:
    # Print the current value of 'counter.'
    print(counter)

    # Check if 'counter' is equal to 4.
    if counter == 4:
        # If 'counter' is 4, exit the loop prematurely.
        break

    # Increment 'counter' by 1 in each iteration.
    counter = counter + 1

10

In [ ]:
# nested for loops

# A list containing lists of names and corresponding numbers.
names = [['Abiodun', 8], ['Sunday', 6], ['Joshua', 7]]

# Outer loop iterating through the sublists within the 'names' list.
for i in names:
    # Printing the current sublist.
    print(f'List = {i}')

    # Inner loop iterating through the items within the current sublist.
    for item in i:
        # Printing each item in the current sublist.
        print(f'items: {item}')
else:
    # This block is executed when both loops complete.
    print('loop is done')

List = ['Abiodun', 8]
items: Abiodun
items: 8
List = ['Sunday', 6]
items: Sunday
items: 6
List = ['Joshua', 7]
items: Joshua
items: 7
loop is done

In [ ]:
for i in range(5): # outer loop is for rows
    for j in range(i + 1): # inner loop for printing asteriks
        print("*", end=" ")
    print() # move to the next line after each row

*
* *
* * *
* * * *
* * * * *

In [ ]:
# Initialize the outer loop counter.
i = 1

# Outer while loop controls the number of rows.
while i <= 5:
    # Initialize the inner loop counter for each row.
    j = 1

    # Inner while loop for printing asterisks in the current row.
    while j <= i:
        # Print an asterisk with a space after it.
        print("*", end=" ")

        # Increment the inner loop counter.
        j += 1

    # Move to the next line after each row.
    print()

    # Increment the outer loop counter to move to the next row.
    i += 1

*
* *
* * *
* * * *
* * * * *